# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-rnaseq-1.3dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - anaconda::openjdk=8.0.152 # Needed for FastQC - conda build hangs without this
  - bioconda::fastqc=0.11.8
  - bioconda::trim-galore=0.5.0
  - bioconda::star=2.6.1b
  - bioconda::hisat2=2.1.0
  - bioconda::picard=2.18.23
  - bioconda::bioconductor-dupradar=1.10.0
  - conda-forge::r-data.table=1.12.0
  - conda-forge::r-gplots=3.0.1
  - bioconda::bioconductor-edger=3.22.5
  - conda-forge::r-markdown=0.9
  - bioconda::csvtk=0.17.0
  - bioconda::preseq=2.0.3
  - bioconda::rseqc=3.0.0
  - bioconda::samtools=1.9
  - bioconda::stringtie=1.3.4
  - bioconda::subread=1.6.3
  - bioconda::gffread=0.9.12
  - bioconda::deeptools=3.1.3
  - bioconda::multiqc=1.7
